version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - redmoogle
  allow:
  - dependency-type: direct
  - dependency-type: indirect
